name: timelapps
description: TimeTimer and NoiseLight

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.4.0
  google_fonts: ^5.1.0
  just_audio: ^0.9.34
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon_timelapps.png"
  adaptive_icon_background: "#DEDEDE"
  adaptive_icon_foreground: "assets/icon_timelapps.png"
  min_sdk_android: 24 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon_timelapps.png"
    background_color: "#DEDEDE"
    theme_color: "#DEDEDE"
  windows:
    generate: true
    image_path: "assets/icon_timelapps.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon_timelapps.png"

flutter_native_splash:
  color: "#dedede"
  image: assets/logo_plotsklapps_stacked.png
  android_12:
    color: "#dedede"
    icon_background_color: "#dedede"
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  fullscreen: true
